version: '3'

services:
  talibookapi:
    image: talibookapi:v1
    environment:
      - APP_ENV=production
      - HTTP_PROTOCOL=http
      - PORT=8000
      - HOST_NAME=192.168.0.120
      - DATABASE_HOST=postgres_db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=TALIBOOK_DB
    depends_on:
      - postgres_db
    ports:
      - 8000:8000

  postgres_db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=TALIBOOK_DB
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
volumes:
  postgres-volume:
